Shopify/roast

- Gemfile
- Gemfile.lock
- lib/roast.rb
- lib/roast/initializers.rb
- lib/roast/tools/search_file.rb
- test/roast/tools/search_file_test.rb
This PR changes the search tool from using `find` to a glob pattern. It also fixes some bugs I found while testing.
- Replaced `find` command with native Ruby `Dir.glob` in SearchFile tool for improved cross-platform compatibility
- Updated SearchFile API to use glob patterns instead of shell pattern matching
- Added ability to specify a search path in SearchFile tool
- Improved error messages in SearchFile with more context about the search
- Changed multiple file results format to use newline-separated paths for better readability
> Improve search tool

- test/roast/tools/search_file_test.rb
Roast::Tools::SearchFile was updated with more specific error messaging, but the test was still testing for the old message.
Relevant code in the source file:
```
rescue StandardError => e
"Error searching for '#{glob_pattern}' in '#{path}': #{e.message}".tap do |error_message|
Roast::Helpers::Logger.error(error_message + "\n")
Roast::Helpers::Logger.debug(e.backtrace.join("\n") + "\n") if ENV["DEBUG"]
end
```
> Fixed failing test caused by out-of-date error message assertion

- README.md
- examples/openrouter_example/README.md
- examples/openrouter_example/analyze_input/prompt.md
- examples/openrouter_example/generate_response/prompt.md
- examples/openrouter_example/workflow.yml
- lib/roast/workflow/configuration.rb
- lib/roast/workflow/configuration_parser.rb
- test/fixtures/files/openrouter_workflow.yml
- test/roast/workflow/configuration_openrouter_test.rb
- test/roast/workflow/configuration_parser_openrouter_test.rb
In order to enable more than just OpenAI as a backend, this commit adds a new api_provider configuration option. This allows us to set openrouter or openai as the provider and correctly set up our model through Raix. It's worth mentioning that the default behavior of OpenAI is preserved and this configuration option should be only additive.
This closes #21
> Feat: Add support for OpenRouter

- test/test_helper.rb
This is a different take on #40 so that we just go back to Minitest's original implementation of `at_exit` so that the Roast test suite exits as expected.
> Restore Minitest at_exit hook for Roast tests

- examples/openrouter_example/workflow.yml
- lib/roast/workflow/base_step.rb
- lib/roast/workflow/base_workflow.rb
- lib/roast/workflow/configuration_parser.rb
- lib/roast/workflow/session_manager.rb
- test/roast/workflow/base_step_test.rb
- test/roast/workflow/configuration_parser_openrouter_test.rb
- Use access_token instead of api_key as an initalizer
- Use a model that exists on openrouter
- Fix passing models to the openrouter client
This fixes #53
> Fix running roast workflows with openrouter 

- lib/roast/workflow/base_workflow.rb
- lib/roast/workflow/session_manager.rb
There are some issues I've encountered while playing with a targetless workflow:
- `null` system prompt:
```
Chat completion failed!!!!!!!!!!!!!!!!: {"error"=>{"message"=>"Invalid value for 'content': expected a string, got null.", "type"=>"invalid_request_error", "param"=>"messages.[0].content", "code"=>nil}}
```
That happens when no workflow prompt exists and no target specified.
- Saving state for targetless executions failed because there is no `file_path`
Fixed both in this PR.
> Targetless fixes

- lib/roast.rb
- lib/roast/workflow/base_workflow.rb
- lib/roast/workflow/configuration_parser.rb
- lib/roast/workflow/workflow_executor.rb
- test/roast/workflow/workflow_executor_test.rb
This PR adds support for a `pause` flag that takes a step name. When that step name comes up it triggers a `binding.irb` session. Fun fact prior to this PR that location had a local variable name called `step` - can you guess what happened when attempting to reference that var? That's right it.....stepped to the next line. 😝 
So in order to mitigate that I also reworked the locals in that method so that there were no collisions. 
Paired on this with @nfgrep 🍐 
Closes #16
> Add pause flag

- lib/roast/workflow/file_state_repository.rb
- test/roast/workflow/file_state_repository_test.rb
Steps can be stored in nested folders and named as `path/to/step.rb`, so we must create intermediate folder when saving the status.
> Fix saving status for path/to/step.rb steps

- Gemfile
- Gemfile.lock
- examples/workflow_generator/README.md
- examples/workflow_generator/analyze_user_request/prompt.md
- examples/workflow_generator/create_workflow_files/prompt.md
- examples/workflow_generator/get_user_input/prompt.md
- examples/workflow_generator/info_from_roast.rb
- examples/workflow_generator/workflow.yml
- lib/roast.rb
- lib/roast/tools.rb
- lib/roast/tools/ask_user.rb
- lib/roast/tools/cmd.rb
- roast.gemspec
You can either:
- Select an existing example from `examples/`.
- Write a prompt for it to generate you a new workflow (currently "beta").
- Added cli-ui as a dependency, was faster+easier than trying to write our own picker TUI.
- Added an `ask_user` tool which prompts the user for some input. Needed this for the "from prompt" workflow to get a prompt from user.
> `roast init`

- README.md
Because Roast on RubyGems is actually `roast-ai` it can sometimes be confusing for folks so let's move the install instructions right to the top of the README. Hopefully this helps people pick the right gem.
> Move install higher in readme

- README.md
- examples/grading/workflow.yml
I wrote a blog post (https://code.dblock.org/2025/05/10/executing-structured-ai-workflows-with-shopify-roast.html) about trying Roast, but don't think it's right to link that from a README. Ported the bare minimum here.
Downgraded models in `examples/grading/workflow.yml` to cheap tier ones.
> Added a Try It section to README.

- lib/roast/tools/search_file.rb
- test/roast/tools/search_file_test.rb
The search_file tool will search for a file using Dir.glob and include a base path if there is one. It will then base the result into read_contents. However, Dir.glob with a base will return results relative to that base, so the read contents will fail.
Many times the LLM will see the resulting error and then use the full path with a base of ., which will work correctly. This should just skip that roundtrip.
> Correctly prefix path when searching for files

- Gemfile.lock
- roast.gemspec
We hit a snag with our projects that use cocoapods where that project has a requirement that activesupport be less than version 8, seen here:
https://rubygems.org/gems/cocoapods-core
So this PR just downgrades activesupport to play nice.
> Downgrade activesupport dependency to 7.0

- .github/workflows/ci.yaml
- .gitignore
- gemfiles/activesupport7.gemfile
- gemfiles/activesupport8.gemfile
- roast.gemspec
I made a mistake on #95 where I locked the project to 7.x of active support instead of allowing versions of at least 7 or greater. Luckily @ericproulx noticed and so this PR fixes that and then also adds active support 7 and 8 to the test matrix so that we can't make this mistake again. That's possibly too far - what do you think?
The way I did this is actually inspired by how @ericproulx did it over on Grape here: https://github.com/ruby-grape/grape/pull/2431. I was about to look into setting up Appraisals and then noticed I could just use this `eval_gemfile` method and keep things simple.
> Add activesupport to testing matrix

- README.md
- lib/roast/value_objects.rb
- lib/roast/value_objects/uri_base.rb
- lib/roast/workflow/api_configuration.rb
- lib/roast/workflow/configuration.rb
- lib/roast/workflow/workflow_initializer.rb
- test/roast/helpers/prompt_loader_test.rb
- test/roast/value_objects/uri_base_test.rb
- test/roast/workflow/configuration_parser_test.rb
- test/roast/workflow/configuration_test.rb
- test/roast/workflow/step_loader_test.rb
- test/roast/workflow/targetless_workflow_test.rb
- test/roast/workflow/workflow_initializer_test.rb
With this you can configure an AI proxy in the workflow.
```yml
uri_base: https://proxy.example.com/v1
```
Feels like maybe it should also be exposed via some command line flag, but also the workflow is a lot more flexible and could use an ENV.
Closes #12.
> Added configurable uri_base.

- lib/roast/workflow/base_iteration_step.rb
- lib/roast/workflow/base_step.rb
- lib/roast/workflow/iteration_executor.rb
- lib/roast/workflow/workflow_executor.rb
- test/roast/workflow/iteration_config_hash_test.rb
- test/roast/workflow/iteration_executor_test.rb
- test/roast/workflow/iteration_step_configuration_test.rb
This PR fixes an issue where nested steps within iteration steps (repeat/each) were not respecting model configuration from the workflow or step level. They would always fall back to the default model.
When `BaseIterationStep` executed nested steps, it created a new `WorkflowExecutor` with an empty config_hash:
```ruby
executor ||= WorkflowExecutor.new(context, {}, context_path)
```
This meant the `StepLoader` couldn't access model configuration, causing it to fall back to the default model.
1. Updated `IterationExecutor` to accept and pass along the config_hash
2. Modified `BaseIterationStep` to store and use the config_hash when creating WorkflowExecutors
3. Updated `WorkflowExecutor` to pass config_hash to IterationExecutor
Added comprehensive unit tests in …
> Fix model inheritance for nested steps in iteration steps

- lib/roast.rb
Solves https://github.com/Shopify/roast/issues/112
Requires `active_support` extensions as the first step while loading `roast` dependencies to solve issues with required `ActiveSupport` modules that could not have been loaded on application that do not load the whole `ActiveSupport`
> [Bug] Require active_support extensions as first dependency when loading roast

- test/roast/cli_test.rb
- test/roast/resources/api_resource_test.rb
- test/roast/tools/search_file_test.rb
- test/roast/workflow/base_step_test.rb
- test/roast/workflow/base_workflow_test.rb
- test/roast/workflow/configuration_parser_openrouter_test.rb
- test/roast/workflow/configuration_parser_test.rb
- test/roast/workflow/error_handler_test.rb
- test/roast/workflow/iteration_config_hash_test.rb
- test/roast/workflow/iteration_executor_test.rb
- test/roast/workflow/output_handler_test.rb
- test/roast/workflow/parallel_executor_test.rb
- test/roast/workflow/replay_handler_test.rb
- test/roast/workflow/targetless_workflow_test.rb
- test/roast/workflow/workflow_initializer_test.rb
- test/roast/workflow/workflow_runner_test.rb
Remove redundant `require "mocha/minitest"` statements from individual test files.
Currently, `mocha/minitest` is required in two places:
1. Once in `test/test_helper.rb` (line 4)
2. Again in individual test files
Since all test files already require `test_helper.rb`, the individual require statements are redundant.
This PR removes `require "mocha/minitest"` from 16 test files:
- `test/roast/cli_test.rb`
- `test/roast/resources/api_resource_test.rb`
- `test/roast/tools/search_file_test.rb`
- `test/roast/workflow/base_step_test.rb`
- `test/roast/workflow/base_workflow_test.rb`
- `test/roast/workflow/configuration_parser_openrouter_test.rb`
- `test/roast/workflow/configuration_parser_test.rb`
- `test/roast/workflow/error_handler_test.rb`
- `test/roast/workflow/iteration_config_hash_test.rb` …
> Require mocha/minitest once in test files

- test/test_helper.rb
I was seeing this warning during tests:
activesupport-8.0.2/lib/active_support.rb:100: warning: previous definition of test_order was here
I checked the git blame, and don't see any background on why this is needed. I'm not sure if it's a bug in ActiveSupport or a bug in our test suite.
This tries to remove it to see if it's still a problem. Some cursory running of the tests does seem to be random (ie different seeds) at least.
> Remove workaround for test order

- README.md
- lib/roast/workflow/step_loader.rb
- test/roast/workflow/pre_post_processing_test.rb
Updating to accept a code path instead of always looking in the same directory. This will allow us to reuse certain steps/methods/code. 
Similar change in `core` https://github.com/shop/world/pull/65063
Examples:
```
model: gpt-4o-mini
tools:
- Roast::Tools::ReadFile
steps:
- read_test_file
read_test_file:
path: ../relative_path/read_test_file    <---- new code/field added
```
```
model: gpt-4o-mini
tools:
- Roast::Tools::ReadFile
steps:
- read_test_file
read_test_file:
path: /absolute_path/read_test_file    <---- new code/field added
```
> Allow per-step path to be specified in the workflow configuration

- README.md
- examples/shared_config/README.md
- examples/shared_config/example_with_shared_config/workflow.yml
- examples/shared_config/shared.yml
- lib/roast/workflow/configuration_loader.rb
- test/roast/workflow/configuration_loader_test.rb
- Add support for `shared.yml` file to define reusable YAML anchors across
workflows
- Enables DRY configuration by allowing common settings to be defined once
and referenced in multiple workflow files
- Modified `ConfigurationLoader#load` to check for `shared.yml` one level
above the workflow directory
- When found, loads `shared.yml` content first, then appends workflow
content, enabling anchor references
- Uses `YAML.load` with `aliases: true` to properly handle YAML anchors
- Added comprehensive example in `examples/shared_config/` demonstrating the
feature
- Updated main README with documentation about shared configuration support
- Includes practical examples of defining common tool lists and reusable
steps
- Added extensive test coverage for the new functionality including:
- …
> Support shared.yml file for reusable YAML anchors

- lib/roast/workflow/base_step.rb
This comes up when running tests:
~/workspace/roast/lib/roast/workflow/base_step.rb:43: warning: method redefined; discarding old chat_completion
~/.local/share/mise/installs/ruby/3.4.2/lib/ruby/3.4.0/forwardable.rb:231: warning: previous definition of chat_completion was here
It's being overriden anyways, so it's safe to remove the initial definition via def_delegator.
> Fix warning: method redefined; discarding old chat_completion

- lib/roast/errors.rb
- lib/roast/workflow/configuration_parser.rb
- lib/roast/workflow/input_step.rb
Pressing Ctrl-C during an input step will exit the CLI instead of showing a huge stack trace
> adds 'exit early' feature to InputStep.

- examples/grading/rb_test_runner
I ran `roast init` in my repo and chose the `grading` example. Then I ran:
`bundle exec roast execute grading/workflow.yml test/models/user_test.rb`
It failed because it couldn't find `minitest_coverage_runner`.
> Fix require path for `minitest_coverage_runner` helper

- lib/roast/tools/coding_agent.rb
- lib/roast/workflow/agent_step.rb
- test/roast/workflow/agent_step_test.rb
Closes #303 
Fixes CodingAgent step crashes when `json: true` is configured by implementing proper JSON parsing.
- **Line 135**: Fixed undefined `line` variable → `json.inspect` in error message
- **Lines 33-59**: Added comprehensive JSON parsing logic that:
- Checks if `@json` is configured and result is a string
- Skips parsing for error messages to avoid confusion
- Strips Markdown code blocks (`````json` and ``````) that Claude commonly wraps JSON in
- Handles both `````json` and plain ````` ``` fenced blocks
- Provides clear error messages for JSON parsing failures
Normal LLM steps automatically get JSON parsing through the Raix gem, but CodingAgent steps bypass this flow by calling
the Claude Code CLI directly. This meant `json: true` configuration was ignored, leading to type …
> Fix JSON parsing for CodingAgent steps

- test/integration/metadata_parallel_test.rb
- test/roast/workflow/workflow_executor_test.rb
- Added integration tests for metadata behaviour during parallel step execution
- Added test for metadata interpolation in workflow expressions using `{{metadata.path.to.value}}` syntax
These tests verify that the metadata system works correctly in more complex scenarios:
1. **Parallel execution tests** verify that:
- Metadata access is thread-safe when steps run in parallel
- Each parallel step can write its own metadata without corruption
- Sequential steps before and after parallel execution can access all metadata
- Thread locals are properly isolated between parallel executions
2. **Interpolation test** verifies that:
- Metadata can be interpolated in step prompts using the same `{{ }}` syntax as output
- Both dot notation (`metadata.step.field`) and bracket notation …
> Add additional metadata integration tests

- README.md
- lib/roast/tools/coding_agent.rb
- lib/roast/workflow/agent_step.rb
- test/roast/tools/coding_agent_options_test.rb
- test/roast/tools/coding_agent_test.rb
- test/roast/workflow/agent_step_test.rb
Closes #302 
- Added `resume` option to agent steps that allows resuming from a specific previous step's Claude Code session
- Modified CodingAgent tool to check metadata for stored session IDs when `continue: true` is specified
- Updated AgentStep to copy session IDs from referenced steps when using the resume option
- Enhanced CodingAgent to use `--resume <session_id>` flag when a session ID is available, falling back to `--continue` otherwise
- Added session ID persistence by extracting and storing session IDs from Claude Code JSON responses
- Added comprehensive tests for the resume functionality
- Updated README with documentation for the new resume option
The existing `continue: true` option only continues from the immediately previous Claude Code session, which can be problematic …
> Add option for coding agent steps to resume specific session

- lib/roast/tools/grep.rb
- lib/roast/workflow/workflow_initializer.rb
- test/roast/tools/grep_test.rb
- test/roast/workflow/file_state_repository_test.rb
- test/roast/workflow/workflow_initializer_test.rb
1. Multiple `include` calls in `workflow_initializer.rb`; e.g.,
```
/Users/travis/.gem/ruby/ruby-3.4.2/gems/raix-openai-eight-1.0.1/lib/raix/function_dispatch.rb:67: warning: method redefined; discarding old search_for_file
/Users/travis/.gem/ruby/ruby-3.4.2/gems/raix-openai-eight-1.0.1/lib/raix/function_dispatch.rb:67: warning: previous definition of search_for_file was here
```
Called out in #120. 
2. `workflow_initializer_test.rb` was not resetting the `BaseWorkflow` constant between tests.
This was a bit complicated, but the tests ended up coupled between execution. This removes that coupling.
Also changed the assertions from what APIs were called to what is the behavior of the targeted object.
(Behaviors vs. implementation.)
3. `warning: redefining 'object_id' may cause serious …
> Test warning clean up

- lib/roast.rb
- test/roast/cli_test.rb
Errors in Roast default to dumping the entire exception. This PR changes the default to be the error message. The full exception is visible in verbose mode (`-v`).
> Shorten error output unless in verbose mode

- lib/roast/workflow/configuration.rb
- lib/roast/workflow/workflow_runner.rb
- test/roast/workflow/pre_post_processing_test.rb
- test/roast/workflow/workflow_runner_test.rb
The pre/post processing blocks are the same for all step types, extract from the `run*` methods.
> Consolidate duplicated pre/post processing code

- dsl/simple.rb
- lib/roast.rb
- lib/roast/dsl.rb
- lib/roast/dsl/executor.rb
- test/roast/dsl/executor_test.rb
Add basic executor for a Ruby DSL. Further steps will be defined in the executor (such as agent definitions and step type inference as with the current yml standard).
This basic version lets us start iterating on the DSL design ([notes from earlier whiteboarding](https://github.com/Shopify/roast/blob/incubate-ruby-dsl/dsl.md?plain=1) with @juniper-shopify and @nfgrep). Nobody should use this yet, which is why it's hidden behind an explicit flag.
With `--executor=dsl`
> Define Ruby DSL executor

- examples/user_input/funny_name/workflow.yml
- test/functional/list_test.rb
- test/functional/version_test.rb
- test/support/functional_test.rb
Write functional tests for `roast list` as an excuse to figure out some test helpers.
Closes https://github.com/Shopify/roast/issues/376
This test demonstrates how to write functional tests for Roast.
- `in_sandbox` shifts execution into an automatically cleaned up temp directory, with the option to create a workflow file. 
- Extensive definitions of yaml and other supporting files can be set up in `FunctionalTest::Workflows`.
- `assert_cli_error` to validate error message output on exit.
> Add tests for `roast list`

- lib/roast.rb
- roast init now creates roast/ directory if it doesn't exist
- Copies examples into roast/ subdirectory instead of current directory
- Makes roast init consistent with roast list command
Fixes #396
> Fix roast init to create workflows in roast/ directory

- lib/roast/workflow/base_step.rb
- lib/roast/workflow/step_loader.rb
- test/roast/workflow/base_step_test.rb
- test/roast/workflow/step_loader_test.rb
Summary
- Remove hardcoded default "anthropic:claude-opus-4".
- Model resolution: explicit param → workflow.model → StepLoader::DEFAULT_MODEL ("gpt-4o-mini").
- Remove default model in StepLoader
> refactor(base_step): use workflow/steploader default model

- README.md
The examples for input steps seem to have incorrect syntax that will call the model instead of prompting the user for input.
Closes https://github.com/Shopify/roast/issues/409
> Fix README examples for input steps

- lib/roast/workflow/base_workflow.rb
- test/roast/workflow/base_workflow_error_handling_test.rb
This PR enhances error messages for API failures by adding contextual information including:
- API endpoint URL
- HTTP status code  
- Response body details
This makes debugging API failures much easier by providing all relevant information in the error message.
1. First, checkout the examples from PR #412 to get the test setup:
```bash
git checkout 09-16-test_add_examples_for_testing_error_handling
```
2. Start the mock server in one terminal:
```bash
ruby examples/test_errors/mock_server.rb
```
3. In another terminal, while still on main (with examples), run:
```bash
export OPENAI_API_BASE="http://localhost:8080/v1/500"
export OPENAI_API_KEY="test-key"
bin/roast execute examples/test_errors/workflow.yml
```
You'll see a generic error like:
```
Error: the server responded with status 500 …
```
> fix: add more detailed response for 500 errors

- dsl/prototype.rb
- lib/roast/dsl/cog/config.rb
- lib/roast/dsl/config_context.rb
- lib/roast/dsl/execution_context.rb
- lib/roast/dsl/executor.rb
- sorbet/rbi/shims/lib/roast/dsl/config_context.rbi
- sorbet/rbi/shims/lib/roast/dsl/execution_context.rbi
Second part of new Roast architecture. Sorbet typechecking will be used as a way to statically validate Roast workflows. Between Ruby syntax checking and Sorbet static analysis, we should be able to completely eliminate the frustrating syntax gotchas with the current default YAML workflow definitions.
Note: RBI shims are a placeholder, these will be replaced in the future with a tapioca compiler that will be able to generate RBIs for any cog.
I experimented with generics to apply types, but it ended up requiring the writing of some really ugly code. RBI generation with tapioca gives more idiomatic Ruby code while still providing the validations we want to supply.
> Set up typechecking for DSL blocks
